version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
      - image: circleci/python:3.7.11

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.cfg" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 setup.py install
            python3 -m pip install -r requirements-tests.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.cfg" }}

      - run:
          name: Check Style (Flake8)
          command: |
            . venv/bin/activate
            flake8

      - run:
          name: Run Tests with Coverage
          command: |
            . venv/bin/activate
            coverage run -m pytest -vv --strict

      - run:
          name: Coverage Report
          command: |
            . venv/bin/activate
            coverage report

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports
